run:
  timeout: 5m
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: go-reloaded
  govet:
    check-shadowing: true
  misspell:
    locale: US
  unused:
    check-exported: false

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - deadcode
    - varcheck
    - structcheck
    - errcheck
    - gosimple
    - staticcheck
  disable:
    - typecheck # Disabled due to Go modules issues in some environments

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: testdata/
      linters:
        - all